[package]
name = "lily-swaybar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
serde = { version = "1.0.208", features = ["serde_derive"] }
serde_json = "1.0.125"
serde_repr = "0.1.19"
